import libs = liboneapi-dpcpp%lib{dpcpp}
import icx  = liboneapi-dpcpp%exe{icx}
import icpx = liboneapi-dpcpp%exe{icpx}

# Host compile test: proves lib{dpcpp}'s exported poptions (-I paths) make
# omp.h discoverable to this test config's own configured compiler, which is
# independent of icx/icpx.
#
./: exe{test-dpcpp}: cxx{omp-include} $libs

testscript{icx}@./:  test = $icx
testscript{icpx}@./: test = $icpx

./: testscript{icx}@./  $icx
./: testscript{icpx}@./ $icpx
