import libs    = liboneapi-ifort%libs{ifort}
import ifx     = liboneapi-ifort%exe{ifx}
import fpp     = liboneapi-ifort%exe{fpp}
import xfortcom = liboneapi-ifort%exe{xfortcom}

./: exe{test-ifort}: cxx{ifort} $libs

testscript{ifx}@./: test = $ifx
testscript{fpp}@./: test = $fpp

./: testscript{ifx}@./ $ifx
./: testscript{fpp}@./ $fpp

# xfortcom is an internal backend invoked by ifx; not tested standalone.
./: $xfortcom
