import mpi     = liboneapi-mpi%libs{mpi}
import mpicxx  = liboneapi-mpi%libs{mpicxx}
import mpifort = liboneapi-mpi%libs{mpifort}
import mpiexec   = liboneapi-mpi%exe{mpiexec}
import impi_info = liboneapi-mpi%exe{impi_info}

./: exe{test-mpi}: cxx{mpi} $mpi

./: exe{test-mpicxx}:
{
  include = ($cc.target.class == 'linux')
}
exe{test-mpicxx}: cxx{mpicxx} $mpicxx

./: exe{test-mpifort}:
{
  include = ($cc.target.class == 'linux')
}
exe{test-mpifort}: cxx{mpifort} $mpifort

testscript{mpiexec}@./:   test = $mpiexec
testscript{impi_info}@./: test = $impi_info

./: testscript{mpiexec}@./   $mpiexec
./: testscript{impi_info}@./ $impi_info
